### ISSUE TITLE
Faction house extension

### ISSUE THREAD

**Issue by Willtom999** [ShockedPlot7560/FactionMaster#10]
fait un plugin maison fac on peux relier avec plugin faction déja existant

**Comment by ShockedPlot7560** [comment]
Je ferais peut-être une extension en effet

**Comment by ShockedPlot7560** [comment]
> fait un plugin maison fac on peux relier avec plugin faction déja existant

Mais si il est relié à un plugin existant, ca sera avec FactionMaster

**Comment by Willtom999** [comment]
possible mettre simplefaction aussi?

**Comment by ShockedPlot7560** [comment]
Non, c'est FactionMaster, si tu veux avoir les maison de faction et utiliser l'extension qui sortira, il faudra utiliser FactionMaster seul plugin compatible.

**Comment by ShockedPlot7560** [comment]
Je te laisserai surveiller le README.md, l'extension sortira prochainement je l'espère

**Comment by Willtom999** [comment]
ok
