### ISSUE TITLE
Plugin doesn't load

### ISSUE THREAD

**Issue by ParadoxPlays** [ShockedPlot7560/FactionMaster#102]
[05:45:47.111] [Server thread/CRITICAL]: Error: "Class "ShockedPlot7560\FactionMaster\libs\JackMD\ConfigUpdater\ConfigUpdater" not found" (EXCEPTION) in "plugins/FactionMaster.phar/src/Manager/ConfigManager" at line 93
--- Stack trace ---
  #0 plugins/FactionMaster.phar/src/FactionMaster(81): ShockedPlot7560\FactionMaster\Manager\ConfigManager::init(object ShockedPlot7560\FactionMaster\FactionMaster#23454)
  #1 pmsrc/src/plugin/PluginBase(95): ShockedPlot7560\FactionMaster\FactionMaster->onLoad()
  #2 pmsrc/src/plugin/PluginManager(214): pocketmine\plugin\PluginBase->__construct(object pocketmine\plugin\PharPluginLoader#23390, object pocketmine\Server#10, object pocketmine\plugin\PluginDescription#23435, string[41] /home/container/plugin_data/FactionMaster, string[49] phar:///home/container/plugins/FactionMaster.phar, object pocketmine\plugin\DiskResourceProvider#23446)
  #3 pmsrc/src/plugin/PluginManager(357): pocketmine\plugin\PluginManager->internalLoadPlugin(string[42] /home/container/plugins/FactionMaster.phar, object pocketmine\plugin\PharPluginLoader#23390, object pocketmine\plugin\PluginDescription#23435)
  #4 pmsrc/src/Server(1003): pocketmine\plugin\PluginManager->loadPlugins(string[24] /home/container/plugins/)
  #5 pmsrc/src/PocketMine(303): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #6 pmsrc/src/PocketMine(326): pocketmine\server()
  #7 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by ShockedPlot7560** [comment]
Please give me your version of FactionMaster

**Comment by ParadoxPlays** [comment]
Version 4.0.0 uploaded 29th of january 2022, official version not a dev or pm build

**Comment by ShockedPlot7560** [comment]
It will fix normally in 4.1.0, actually in pre-release : https://github.com/FactionMaster/FactionMaster/releases/tag/v4.1.0-dev01
