### ISSUE TITLE
plugin causes server to close when you try to manage permissions on a faction

### ISSUE THREAD

**Issue by ParadoxPlays** [ShockedPlot7560/FactionMaster#103]
[00:56:28.602] [Server thread/CRITICAL]: ErrorException: "Undefined array key "MANAGE_PERMISSIONS_MAIN_TITLE"" (EXCEPTION) in "plugins/FactionMaster (1).phar/src/Manager/TranslationManager" at line 43
--- Stack trace ---
  #0 plugins/FactionMaster (1).phar/src/Manager/TranslationManager(43): pocketmine\errorhandler\ErrorToExceptionHandler::handle(integer 2, string[51] Undefined array key "MANAGE_PERMISSIONS_MAIN_TITLE", string[88] phar:///home/container/plugins/FactionMaster (1).phar/src/Manager/TranslationMan, integer 43)
  #1 plugins/FactionMaster (1).phar/src/Utils/Utils(158): ShockedPlot7560\FactionMaster\Manager\TranslationManager::getTranslation(string[29] MANAGE_PERMISSIONS_MAIN_TITLE, string[2] EN)
  #2 plugins/FactionMaster (1).phar/src/Route/PermissionChangeRoute(138): ShockedPlot7560\FactionMaster\Utils\Utils::getText(string[15] RustlingBrick86, string[29] MANAGE_PERMISSIONS_MAIN_TITLE)
  #3 plugins/FactionMaster (1).phar/src/Route/PermissionChangeRoute(99): ShockedPlot7560\FactionMaster\Route\PermissionChangeRoute->getForm()
  #4 plugins/FactionMaster (1).phar/src/Utils/Utils(99): ShockedPlot7560\FactionMaster\Route\PermissionChangeRoute->__invoke(object pocketmine\player\Player#29766, object ShockedPlot7560\FactionMaster\Database\Entity\UserEntity#99400, array[0], array[1])
  #5 plugins/FactionMaster (1).phar/src/Button/ChangePermission(48): ShockedPlot7560\FactionMaster\Utils\Utils::processMenu(object ShockedPlot7560\FactionMaster\Route\PermissionChangeRoute#25129, object pocketmine\player\Player#29766, array[1])
  #6 plugins/FactionMaster (1).phar/src/Button/Button(134): ShockedPlot7560\FactionMaster\Button\ChangePermission->ShockedPlot7560\FactionMaster\Button\{closure}(object pocketmine\player\Player#29766)
  #7 plugins/FactionMaster (1).phar/src/Button/Collection/Collection(96): ShockedPlot7560\FactionMaster\Button\Button->call(object pocketmine\player\Player#29766)
  #8 plugins/FactionMaster (1).phar/src/Route/ManagePermissionRoute(81): ShockedPlot7560\FactionMaster\Button\Collection\Collection->process(integer 1, object pocketmine\player\Player#29766)
  #9 plugins/FactionMaster (1).phar/src/libs/Vecnavium/FormsUI/Form(46): ShockedPlot7560\FactionMaster\Route\ManagePermissionRoute->ShockedPlot7560\FactionMaster\Route\{closure}(object pocketmine\player\Player#29766, integer 1)
  #10 pmsrc/src/player/Player(1985): ShockedPlot7560\FactionMaster\libs\Vecnavium\FormsUI\Form->handleResponse(object pocketmine\player\Player#29766, integer 1)
  #11 pmsrc/src/network/mcpe/handler/InGamePacketHandler(892): pocketmine\player\Player->onFormSubmit(integer 1, integer 1)
  #12 pmsrc/vendor/pocketmine/bedrock-protocol/src/ModalFormResponsePacket(46): pocketmine\network\mcpe\handler\InGamePacketHandler->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#99331)
  #13 pmsrc/src/network/mcpe/NetworkSession(395): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#101971)
  #14 pmsrc/src/network/mcpe/NetworkSession(358): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#99331, string[5] e..1.)
  #15 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[8] cMed2...)
  #16 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[17] ..........o."....)
  #17 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#28219)
  #18 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #19 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #20 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1644368188.6068)
  #21 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #22 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #23 pmsrc/src/PocketMine(327): pocketmine\server()
  #24 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by ParadoxPlays** [comment]
hello?

**Comment by ShockedPlot7560** [comment]
Which version did you use ? The 4.0 ?

**Comment by ParadoxPlays** [comment]
I'm on the version you told me to switch to in my last issue about the plugin not working

**Comment by ParadoxPlays** [comment]
that appears in console whenever I go to the permissions thing on the manage ui and hit any of the 3 roles to manage their perms

**Comment by ShockedPlot7560** [comment]
I will check it later
