### ISSUE TITLE
PureChat for FactionMaster

### ISSUE THREAD

**Issue by TlooToonsMC** [ShockedPlot7560/FactionMaster#104]
PureChat for FactionMaster

**Comment by ShockedPlot7560** [comment]
https://github.com/FactionMaster/PureChat/releases/tag/v2.0.0

**Comment by TlooToonsMC** [comment]
api 3

**Comment by TlooToonsMC** [comment]
> https://github.com/FactionMaster/PureChat/releases/tag/v2.0.0
api 3

**Comment by ShockedPlot7560** [comment]
As PM3 is no longer supported and has been deprecated for many months. This issue is no longer supported.   
We will no longer maintain version 3.0 of FactionMaster.
