### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Tuvqlu** [ShockedPlot7560/FactionMaster#107]
Crashes when you upload newest version to your server
**To Reproduce**
1. Upload plugin to your server 

**Expected behavior**
The plugin to work and not crash 
**Screenshots**
![image](https://user-images.githubusercontent.com/98550458/154325218-4427ed04-7d08-4f0f-9b35-1efbe445b231.jpeg)
**System (please complete the following information):**
    * FactionMaster
    * PocketMine
    * Version of possible extension
 - PHP version
 - Plugin installed=

**Additional context**

**Comment by ShockedPlot7560** [comment]
Which provider have you set in you config for database ? MYSQL ou SQLITE ?

**Comment by Tuvqlu** [comment]
I didn't edit config, I didn't have the chance because I have to restart the server before config pops up.

**Comment by ShockedPlot7560** [comment]
Will be fixed in the next release of 4.1 on poggit
