### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by KingboiDre** [ShockedPlot7560/FactionMaster#11]
Add value like sky block but in claims. 
Any valuable block placed in the claim are counted which will be used for /f top 
Valuable blocks can be set in config. 
I can implement this if you want 😊

**Comment by ShockedPlot7560** [comment]
Hmmm, indeed its a good idea, you can try to implements you if you want and made a PR when is done. We will see at this time. 
Just one contrary I give. That the user in the config file can choose if he wants this feature or not. And why not another config file that would list all the desired blocks that give points and how many

**Comment by ShockedPlot7560** [comment]
Doing an extension is more sensible I think if it is possible with the idea you have in mind

**Comment by KingboiDre** [comment]
Making it able to toggle on or off is gonna be kinda hard but I'll try

**Comment by ShockedPlot7560** [comment]
This will not be done internally after all, however if you wish to add this feature, I invite you to look at creating a FactionMaster extension and sharing it, this one can be published officially if it meets all the criteria of poggit and FactionMaster together.
