### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Willtom999** [ShockedPlot7560/FactionMaster#12]
Tu pourrais fair un peu comme le plugin de ayzrix son faction car il est bien est styler genre

**Comment by Willtom999** [comment]
Textfloating , Config dû faction mysql support déjà mis je pense

**Comment by ShockedPlot7560** [comment]
> Tu pourrais fair un peu comme le plugin de ayzrix son faction car il est bien est styler genre

Le but n'est pas de copier les autres mais bien de proposer quelque chose d'un peu plus différent.

> Textfloating , Config dû faction mysql support déjà mis je pense

Fait une extension sera possible oui pour les textfloating, mais cela ne sera pas mis dans le plugin principal

**Comment by Willtom999** [comment]
Rajouter Le nombre de personne max dans une faction dans la Config

**Comment by Willtom999** [comment]
![6B6E2441-D5D0-4E02-B0FB-893AA4BE036E](https://user-images.githubusercontent.com/83521998/131495620-b9505f82-27bd-4d4c-a439-c353dd01e283.png)

**Comment by Willtom999** [comment]
/f admin avec ui pour les admin on peux se téléporte aux homes des factions

**Comment by Willtom999** [comment]
ou descendre le power ou est le power d’une faction

**Comment by ShockedPlot7560** [comment]
> Rajouter Le nombre de personne max dans une faction dans la Config

https://github.com/ShockedPlot7560/FactionMaster/blob/master/resources/config.yml#L49

**Comment by ShockedPlot7560** [comment]
> /f admin avec ui pour les admin on peux se téléporte aux homes des factions

une extension sera disponible pour ceci oui

**Comment by ShockedPlot7560** [comment]
> https://github.com/ShockedPlot7560/FactionMaster/issues/12#issuecomment-909153755

Ce n'est pas le fichier de config de FactionMaster
