### ISSUE TITLE
Leaderboard menu choice untraslated

### ISSUE THREAD

**Issue by MrBlasyMSK** [ShockedPlot7560/FactionMaster#124]
**Describe the bug**
The plugin is writed in Spanish for display this:
```yml
BUTTON_LEADERBOARD_FACTIONLEVEL: "Clasificación por nivel"
BUTTON_LEADERBOARD_FACTIONPOWER: "Clasificación por poder"
```
But it display this
![image](https://user-images.githubusercontent.com/85447029/158449746-d4f874e9-9c14-481d-8ed4-417e3059be1d.png)

**To Reproduce**
1. Put your lang in Spanish and check the leaderboard

**Expected behavior**
X

**Screenshots**
Screenshot at topside

**System (please complete the following information):**
 - OS: Ubuntu
 - Version dev214
    * FactionMaster 4.2.1
    * PocketMine 4.2.3
    * Version of possible extension X
 - PHP version 8.0.16
 - Plugin installed=
Plugins (31): AdvanceDeaths v3.5, BedrockEconomy v2.0.7, BetterBan v4.1.1, BuilderTools v1.4.0-dev, CapesLocker v1.2.0, ChatThin v1.3.0, CustomMessages v1.0.1, DevTools v1.15.0, FactionMaster v4.2.1, FormAPI v2.1.0, InvSee v2.0.1, KygekPingTPS v2.0.0, LoadEveryWorlds v1.0.1, MOTDShuffle v1.3.0, Mobs v1.1.0, MultiWorld v1.7.0-beta4, MyPlot v2.1.0, Netherite v2.3, NoVoid v1.0.0, PiggyCustomEnchants v3.0.0, PlayerTags v2.0.0, PurePerms v2.0.2, PurePermsScore v2.0.0, RedstoneCircuit v3.0.3, ScoreHud v7.0.0, SimpleNPC v3.0.1, VanillaElytra v1.4.0, VanishV2 v3.1.0, Weather v1.0.4, Worlds v3.1.0, theSpawn v1.7.0-dev

**Additional context**

**Comment by ShockedPlot7560** [comment]
Indeed, this is not translated.
However, the behavior is not really that. On this page are the leaderboard ids and not their translation, and the translation is normally found in the title, once the leaderboard is selected.
If this could be confirmed it would be great, otherwise it will be corrected in the future update.

**Comment by MrBlasyMSK** [comment]
> Indeed, this is not translated. However, the behavior is not really that. On this page are the leaderboard ids and not their translation, and the translation is normally found in the title, once the leaderboard is selected. If this could be confirmed it would be great, otherwise it will be corrected in the future update.

https://streamable.com/1030q8 u mean this?

**Comment by ShockedPlot7560** [comment]
ok I see the problem, it will be fixed in the next update
