### ISSUE TITLE
Add phrase when not being able to teleport with /f home

### ISSUE THREAD

**Issue by MrBlasyMSK** [ShockedPlot7560/FactionMaster#126]
**Is your feature request related to a problem? Please describe.**
If a player tries to tp the faction home with /f home and the world is not loaded, it would be nice if a message appears to the player.
Something like:

`You could not tp your home because the world is not loaded or does not exist`

So by some chance if the world is deleted or simply not loaded, the player gets an answer as to why he can't go home.

**Describe the solution you'd like**
X

**Describe alternatives you've considered**
X

**Additional context**
X

**Comment by ShockedPlot7560** [comment]
This can indeed be a good idea

**Comment by ShockedPlot7560** [comment]
Fixes in 0767a768ad70768e66392427676dd3316c5dde87
