### ISSUE TITLE
MONEY CRASH

### ISSUE THREAD

**Issue by Tuvqlu** [ShockedPlot7560/FactionMaster#130]
This plugin crashes when you open the factionmoney leaderboard button and the lang change does not change on those buttons

**To Reproduce**
1. Download PL
2. Download Faction Bank
3. Add to your server!
4. Open UI
5. click leaderboard
6. click money
7. CRASH

**Expected behavior**
Me to see this beautiful money lb.

**Screenshots**

**System (please complete the following information):**
 -]
 - Version 4.2.6 (1.18.1
    * FactionMaster
    * PocketMine
    * Version of possible extension
 - PHP version
 - Plugin installed= faction master, bank, invitation improve

**Additional context**

**Comment by ShockedPlot7560** [comment]
Please open this issue in the correct repository
