### ISSUE TITLE
Faction power is not increasing

### ISSUE THREAD

**Issue by justin-eckenweber** [ShockedPlot7560/FactionMaster#136]
The faction power is not increasing when killing someone. So we can't level up our factions.
Can you fix that?

**Comment by ShockedPlot7560** [comment]
Hello,

Did you put a power > 0 in the configuration file.

Moreover, if you want to gain power thanks to the no stuff (not activated) you have to do it in the configuration file.

**Comment by justin-eckenweber** [comment]
It is the default config. Oh I see someone needs armor. Yeah now it works.
And how can I levelup now? With my power?

**Comment by ShockedPlot7560** [comment]
You can level up by killing people, you win experience with it (see configuration file for more information)

**Comment by justin-eckenweber** [comment]
Alright thank you very much!
