### ISSUE TITLE
Unlimited Power Bug

### ISSUE THREAD

**Issue by justin-eckenweber** [ShockedPlot7560/FactionMaster#138]
Hi, 

one of our users reported that they are able to generate unlimited faction power, here is the way to do it:
Have a faction and ally with an other one (+100 power). Then delete the faction you made the ally with and you will keep the power.
You can repeat this unlimited times and generate unlimited power... 

Can you fix that? We have the newest version.

**Comment by ShockedPlot7560** [comment]
Hi!
I don't see how you can gain power from alliances knowing that when you ally, you don't gain power.

**Comment by justin-eckenweber** [comment]
Oh you are right. Sorry one of my users told me something wrong then.
I tested it myself and yes it did not work. Sorry for that!
