### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by Willtom999** [ShockedPlot7560/FactionMaster#16]
Rajouter purechat et nametag pour la faction s’affiche

**Comment by ShockedPlot7560** [comment]
This feature will not be added due to the incompatibility of PurePerms with new versions of PocketMine and therefore PureChat. It is necessary for FactionMaster to be able to ensure compatibility for new versions.

**Comment by mesiiiiiii** [comment]
honestly that sucks better something than nothing

**Comment by ShockedPlot7560** [comment]
Propose a plugin compatible with the latest version of pocketmine, currently 3.22

**Comment by ShockedPlot7560** [comment]
> https://github.com/ShockedPlot7560/FactionMaster/issues/19#issuecomment-913781123

Most importantly, PureChat currently does not accept the addition of any other faction plugin than the basic ones. Provide me with a plugin that does and I will adapt it

**Comment by mesiiiiiii** [comment]
Purechat doesnt works? It works on all my servers and you dont need to add an addon just fork purechat like wertzui did it with his clans plugin, but you decide its ok.

**Comment by ShockedPlot7560** [comment]
I will check again
