### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by NoSoyJorgeXD** [ShockedPlot7560/FactionMaster#18]
Hello, I open this issue to suggest a translation to the Spanish language

**Comment by ShockedPlot7560** [comment]
No problem, as I don't have any collaborators in Spanish at the moment, you can do it if you want. If the translation is complete after proofreading, you will be counted as a contributor.

**Comment by NoSoyJorgeXD** [comment]
Ok I'm going to translate it into Spanish and attach the file ;)

**Comment by ShockedPlot7560** [comment]
thank you for everyone

**Comment by MrBlasyMSK** [comment]
@NoSoyJorgeXD This has been added in the latest version

You can close this issue whenever you want
