### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ErwanScraft** [ShockedPlot7560/FactionMaster#19]
Please make this fraction support purechat and ScoreHud V6

**Comment by ShockedPlot7560** [comment]
This will be implemented in the next release

**Comment by ErwanScraft** [comment]
And can you add Indonesian?

**Comment by ShockedPlot7560** [comment]
If you want the indonesian, you will have to do it by yourself, by creating a Pull Request with the corresponding file, or wait for a community member to do it.

**Comment by ShockedPlot7560** [comment]
I regret to say that Purechat support will not be possible.
Let me explain: 
* PureChat, requires PurePerm which is not compatible with all the versions that FactionMaster supports.
For the sake of compatibility, we have chosen not to add it until this compatibility is fixed.
However, support for ScoreHUD v6.0.0 will be included in the next release, which is currently being tested.

**Comment by ShockedPlot7560** [comment]
And most importantly, PureChat currently does not accept the addition of any other faction plugin than the basic ones. Provide me with a plugin that does and I will adapt it
