### ISSUE TITLE
Eror

### ISSUE THREAD

**Issue by ErwanScraft** [ShockedPlot7560/FactionMaster#24]
I've tried using FactionMaster_dev-63
And I found an error when I tried to make a faction description, suddenly the server restarted and I found an error like this.

PocketMine-MP Crash Dump Mon Sep 6 22:29:45 CDT 2021

Error: Argument 2 passed to Ifera\ScoreHud\scoreboard\ScoreTag::__construct() must be of the type string, null given, called in phar:///home/container/plugins/FactionMaster_dev-63.phar/src/ShockedPlot7560/FactionMaster/Listener/ScoreHudListener.php on line 470
File: plugins/ScoreHud_dev-70.phar/src/Ifera/ScoreHud/scoreboard/ScoreTag
Line: 43
Type: TypeError

**Comment by ErwanScraft** [comment]
And when I installed the factionmaster textures pack and edited the config.yml image to true, there is a notification like this.

![IMG_20210907_115634](https://user-images.githubusercontent.com/72255518/132286786-eebe44fe-9889-4715-87a7-dc826c23ecc8.jpg)

And when I restart the server, the image setting in the config goes to false

**Comment by ErwanScraft** [comment]
![IMG_20210907_115658](https://user-images.githubusercontent.com/72255518/132286965-800f1d6c-dc1c-48d3-ab34-6a218c111d90.jpg)

**Comment by ShockedPlot7560** [comment]
Ok, thanks, i will fix it

**Comment by ShockedPlot7560** [comment]
> And when I installed the factionmaster textures pack and edited the config.yml image to true, there is a notification like this.
> 
> ![IMG_20210907_115634](https://user-images.githubusercontent.com/72255518/132286786-eebe44fe-9889-4715-87a7-dc826c23ecc8.jpg)
> 
> And when I restart the server, the image setting in the config goes to false

For this, check you have change resource_packs.yml

**Comment by ShockedPlot7560** [comment]
I reinstalled the dev build 63 from scratch, and by modifying well the resource_packs.yml it works very well.

If you have more information or this is settled, I invite you to close this issue

**Comment by ErwanScraft** [comment]
> > And when I installed the factionmaster textures pack and edited the config.yml image to true, there is a notification like this.
> > ![IMG_20210907_115634](https://user-images.githubusercontent.com/72255518/132286786-eebe44fe-9889-4715-87a7-dc826c23ecc8.jpg)
> > And when I restart the server, the image setting in the config goes to false
> 
> For this, check you have change resource_packs.yml

![IMG_20210907_140127](https://user-images.githubusercontent.com/72255518/132299234-b14a2605-7bdd-42e0-bb6f-0357def1d387.jpg)

**Comment by ErwanScraft** [comment]
Is there something wrong? Because I still can't use the resource pack

**Comment by ShockedPlot7560** [comment]
i will check again, thanks for report

**Comment by ShockedPlot7560** [comment]
Have you download the last pack [FactionMaster.zip](https://github.com/ShockedPlot7560/FactionMaster/files/7119685/FactionMaster.zip)
? because it have change to support spanish flag

**Comment by ErwanScraft** [comment]
> Have you download the last pack [FactionMaster.zip](https://github.com/ShockedPlot7560/FactionMaster/files/7119685/FactionMaster.zip)
> ? because it have change to support spanish flag

Oh yes, thank you, and one more thing how I delete the leaderboard that I have created.

![Screenshot_2021-09-07-12-06-07-138_com mojang minecraftpe](https://user-images.githubusercontent.com/72255518/132301918-46c6e48c-6480-4186-af67-b23c008d6144.jpg)

Is there a feature like deleting the leaderboard or do I have to do it in the config settings

**Comment by ErwanScraft** [comment]
I was too careless to make 2 leaderboards in the same place

**Comment by ShockedPlot7560** [comment]
when you are typing /f scoreboard, if you didn't want of the second, restart your server, i will fix that in the next release

**Comment by ErwanScraft** [comment]
Thanks for the help, I really like this plugin
