### ISSUE TITLE
Doesn't ask to download texture pack when I reload

### ISSUE THREAD

**Issue by MrBlasyMSK** [ShockedPlot7560/FactionMaster#40]
40 minutes ago when I reported the bug that the textures did not appear, I downloaded the pack at join

But now when I restart (and I should miss downloading the texture pack) it does not ask me

Is there a problem or am I doing something wrong?

**Comment by ShockedPlot7560** [comment]
> 40 minutes ago when I reported the bug that the textures did not appear, I downloaded the pack at join
> 
> But now when I restart (and I should miss downloading the texture pack) it does not ask me
> 
> Is there a problem or am I doing something wrong?

If you have already downloaded the pack at the entrance and the pack has not changed, it will not be requested again. If the pack is changed intentionally by me, the UUID will be changed and a notification will be put in the console if the wrong pack is on the server

**Comment by MrBlasyMSK** [comment]
Well, the UI interface with buttons still does not appear

**Comment by ShockedPlot7560** [comment]
> Well, the UI interface with buttons still does not appear

Do you have the: 'active-image' in the configuration file set to true?

**Comment by MrBlasyMSK** [comment]
```yml
# If it set to true, image will be display near button
# If it set to false, image will be disabled
active-image: true
```

**Comment by ShockedPlot7560** [comment]
> ```yaml
> # If it set to true, image will be display near button
> # If it set to false, image will be disabled
> active-image: true
> ```

Are the images displayed in purple/black, or is there nothing at all?

**Comment by MrBlasyMSK** [comment]
![image](https://user-images.githubusercontent.com/85447029/132586267-664426c8-4817-457d-becc-164d9640983e.png)

**Comment by MrBlasyMSK** [comment]
Its the dev 75

**Comment by ShockedPlot7560** [comment]
strange, i will check
