### ISSUE TITLE
The plugin removes some NPCs

### ISSUE THREAD

**Issue by MrBlasyMSK** [ShockedPlot7560/FactionMaster#42]
Before you think I'm crazy, I want to warn you that some plugins, for some strange reason, remove some npcs.

It doesn't make much sense for this to happen, since the plugin has nothing to do with NPCs, but this has happened to me before with the "TNTTag" plugin in poggit.

So you can see that I'm not lying to you, I'm going to leave you a test video.

https://streamable.com/n7stmy

Everything is explained in the video, if you have any questions tell me
I report this bug because before I did not use this plugin and that did not happen to me, but since I put it it has started to happen to me

SimpleNPC version: https://poggit.pmmp.io/r/131914/SimpleNPC_dev-288.phar
FactionMaster version: dev75

**Comment by ShockedPlot7560** [comment]
ok, I'll check it out

**Comment by ShockedPlot7560** [comment]
I found the source, instead of clearing entities requiring a clear created by FactionMaster, it was clearing general purpose entities, thanks for reporting this!
