### ISSUE TITLE
The plugins still removing NPCs

### ISSUE THREAD

**Issue by MrBlasyMSK** [ShockedPlot7560/FactionMaster#43]
issue #42 still removing npcs after restart

**Comment by mesiiiiiii** [comment]
Also
/f scoreboard (top faction leaderboard)
and resource pack doesnt works, i will open an issue with more info later if this isnt enough

**Comment by ShockedPlot7560** [comment]
Resource pack works fine for me. I will check for scoreboard.
Download the pack available here https://github.com/ShockedPlot7560/FactionMaster/blob/stable/FactionMaster.zip

**Comment by mesiiiiiii** [comment]
Oh yes i had an outdated version of the resource pack my bad. But /f scoreboard stills dont work for me. I have the leaderboard enabled on config.yml and restarted the server, also the offciial extensions FactionMasterBank and FastionMasterInvitationImprove dont work. I will open an issue with more info right now.

**Comment by ShockedPlot7560** [comment]
For the extension, i know. With the lot of API change this last day, they are actually outdated
