### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by Willtom999** [ShockedPlot7560/FactionMaster#50]
/f map on/off pour faciliter le pillage tu met une permission genre si tu le veux pas tu met pas la permission au joueur

**Comment by Willtom999** [comment]
And add /f border pour voir la limitation des claim ou des chunks du server

**Comment by Willtom999** [comment]
Add /f transfer pour transférer la status du leader a une autre personne

**Comment by Willtom999** [comment]
/f promote mettre quelqu’un grade officier
/ f demote enlever le grade officier

**Comment by Willtom999** [comment]
/f ban - ban quelqu’un de ta faction 
/f kick - kick quelqu’un de ta faction
/f unban - enlever une personne ban

**Comment by Willtom999** [comment]
/f invite pour inviter quelqu’un 
/f chat changer le chat normal en faction pour parler avec ta fac
/f alliés

**Comment by ShockedPlot7560** [comment]
Merci de regarde l'intitulé du plugin. En aucun cas je rajouterais cest commande tout est disponible via panel.

**Comment by Willtom999** [comment]
ok

**Comment by ShockedPlot7560** [comment]
Je me demande si tu test vraiment le plugin, car tout ce que tu énonce dans la majorité est disponible déjà.

**Comment by Willtom999** [comment]
Oui je test vraiment
