### ISSUE TITLE
Internal Server eror

### ISSUE THREAD

**Issue by ErwanScraft** [ShockedPlot7560/FactionMaster#52]
I'm having a problem when I try to summon the faction's top floating text, I get an error like this

![Screenshot_2021-09-23-14-38-33-703_com android chrome](https://user-images.githubusercontent.com/72255518/134470943-d1aa0c84-a9f8-4b08-b89f-37ecf2950715.jpg)

I'm using the latest developer version of the plugin

**Comment by ShockedPlot7560** [comment]
It will be fix in the v3.0.0. It will be release soon, I would like for the next weekend

**Comment by Jesus51-alt** [comment]
The same thing happens to me, update 1.17.30 plssssss 🙏

**Comment by ShockedPlot7560** [comment]
i will update the 2 version to fix this crash, but 3.0.0 will be release soon with more stability.

**Comment by ShockedPlot7560** [comment]
Because of the v3.0.0 in pre-released on poggit, i can't update previous version, so you can use the phar located in this [release](https://github.com/ShockedPlot7560/FactionMaster/releases/tag/v2.4.1)

Thanks well for the report and enjoy !
