### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vJorgee** [ShockedPlot7560/FactionMaster#54]
You have to put an api and make the name of the faction appear in a scoreboard

Like that 
![image](https://user-images.githubusercontent.com/74513442/134827613-28ec250d-e669-43bb-b2eb-dc597837a3f4.png)

**Comment by ShockedPlot7560** [comment]
Display is already possible with ScoreHUD. What is the request, for which plugin, because there is already an API of the same type

**Comment by ShockedPlot7560** [comment]
@NoSoyJorgeXD
