### ISSUE TITLE
Les commandes sont pas encore mis 

### ISSUE THREAD

**Issue by Willtom999** [ShockedPlot7560/FactionMaster#55]
Vous pouvez mettre les subcommande de faction svp

**Comment by ShockedPlot7560** [comment]
Merci de préciser la version utilisé

**Comment by Willtom999** [comment]
versio recente @ShockedPlot7560

**Comment by ShockedPlot7560** [comment]
LE NUMERO ! merci d'avance
les récentes, ca peut être tout

**Comment by Willtom999** [comment]
2.4.1 @ShockedPlot7560

**Comment by ShockedPlot7560** [comment]
V3.0.0 est sorti en pre release, cela fix normalement ce bug qui n'est pas présent pour ma part.
