### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by DPG896** [ShockedPlot7560/FactionMaster#59]
The first load of plugin, itworks fine and i joined, it stopped, i reload the server then this error code popped up![Screenshot_20211004-093610.png](https://user-images.githubusercontent.com/82310008/135781719-f049ccde-068b-4841-948b-31ccfeb9a726.png)![Screenshot_20211004-093621.png](https://user-images.githubusercontent.com/82310008/135781722-5cbc5210-e59c-4024-a668-7496a50c20d9.png)

**Comment by ShockedPlot7560** [comment]
I will fix this in a future update in one day maximum

**Comment by DPG896** [comment]
Thanks :)
