### ISSUE TITLE
how to handle it?

### ISSUE THREAD

**Issue by rokibot009** [ShockedPlot7560/FactionMaster#64]
2021-10-13 [07:18:05] [Server thread/INFO]: Loading FactionMaster v3.1.3
--
  | 2021-10-13 [07:18:05] [Server thread/CRITICAL]: [FactionMaster] FactionMaster 3.0.0 was not compatible with the anterior version, please remake all the installation before launch the server
  | 2021-10-13 [07:18:05] [Server thread/CRITICAL]: [FactionMaster] For precaution, factionMaster will bbe disabled now

how to handle it?

**Comment by ShockedPlot7560** [comment]
This error is caused by the version.yml file being empty. You need to remove the file and normally this will be fixed.

**Comment by ShockedPlot7560** [comment]
I will work on a patch
