### ISSUE TITLE
/f top Feature

### ISSUE THREAD

**Issue by YT-Duckyyy** [ShockedPlot7560/FactionMaster#99]
Can you please add a /f top. This is basically a /f placeleaderboard (type), however it appears in chat like the image provided. 

To commands would be amazing: /f top Power, /f top Levels.
![20211210_204640](https://user-images.githubusercontent.com/97541939/148982831-a2295da0-0422-4105-9da5-d52c2f7f8032.JPG)

Please add this, it would be great and very useful.

**Comment by ShockedPlot7560** [comment]
This can be a feature in more for the 4.1 yes with the leaderboard's menu.

**Comment by YT-Duckyyy** [comment]
Thank you, make it configurable too please just like current leaderboards. Is there any eta for 4.1?

**Comment by ShockedPlot7560** [comment]
No due date for the moment, for the next week / month i think

**Comment by YT-Duckyyy** [comment]
Alright, can you keep my updated please? So I can prepare my server for it.

**Comment by ShockedPlot7560** [comment]
You can join our discord server to keep you up to date

**Comment by YT-Duckyyy** [comment]
Can you send me the link?

**Comment by ShockedPlot7560** [comment]
> Can you send me the link?

https://discord.gg/FrjX6WEpbD

**Comment by ShockedPlot7560** [comment]
@YT-Duckyyy you can DM me on Discord : ShockedPlot7560 # 9999 in respond of you comment on poggit : )
